<?php

/**
 * @file
 * ind_data_md_2020.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function ind_data_md_2020_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_com_non_wrk_supports'.
  $field_bases['field_com_non_wrk_supports'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_com_non_wrk_supports',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'remote' => 'Remote supports',
        'in person' => 'In person supports',
        'remote and in person' => 'Both remote and in person supports',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_fac_non_work_supports'.
  $field_bases['field_fac_non_work_supports'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_fac_non_work_supports',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'remote' => 'Remote supports',
        'in person' => 'In person supports',
        'remote and in person' => 'Both remote and in person supports',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_grp_integ_covid'.
  $field_bases['field_grp_integ_covid'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_grp_integ_covid',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'no' => 'No',
        'yes furlough' => 'Yes - Furloughed (a temporary lay off from work)',
        'yes laid off' => 'Yes - Laid off (terminated without a specific commitment to return',
        'yes voluntary' => 'Yes - Voluntarily not working',
        'yes other' => 'Yes - Other',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_grp_integ_supports'.
  $field_bases['field_grp_integ_supports'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_grp_integ_supports',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'remote' => 'Remote supports',
        'in person' => 'In person supports',
        'remote and in person' => 'Both remote and in person supports',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_indv_comp_covid'.
  $field_bases['field_indv_comp_covid'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_indv_comp_covid',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'no' => 'No',
        'yes furlough' => 'Yes - Furloughed (a temporary lay off from work)',
        'yes laid off' => 'Yes - Laid off (terminated without a specific commitment to return',
        'yes voluntary' => 'Yes - Voluntarily not working',
        'yes other' => 'Yes - Other',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_indv_comp_supports'.
  $field_bases['field_indv_comp_supports'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_indv_comp_supports',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'remote' => 'Remote supports',
        'in person' => 'In person supports',
        'remote and in person' => 'Both remote and in person supports',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_indv_cont_covid'.
  $field_bases['field_indv_cont_covid'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_indv_cont_covid',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'no' => 'No',
        'yes furlough' => 'Yes - Furloughed (a temporary lay off from work)',
        'yes laid off' => 'Yes - Laid off (terminated without a specific commitment to return',
        'yes voluntary' => 'Yes - Voluntarily not working',
        'yes other' => 'Yes - Other',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_indv_cont_supports'.
  $field_bases['field_indv_cont_supports'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_indv_cont_supports',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'remote' => 'Remote supports',
        'in person' => 'In person supports',
        'remote and in person' => 'Both remote and in person supports',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_self_emp_supports'.
  $field_bases['field_self_emp_supports'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_self_emp_supports',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'remote' => 'Remote supports',
        'in person' => 'In person supports',
        'remote and in person' => 'Both remote and in person supports',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_shl_supports'.
  $field_bases['field_shl_supports'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_shl_supports',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'remote' => 'Remote supports',
        'in person' => 'In person supports',
        'remote and in person' => 'Both remote and in person supports',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
