<?php

/**
 * @file
 * individual.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function individual_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_cie_individual'.
  $field_bases['field_cie_individual'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_cie_individual',
    'field_permissions' => array(
      'type' => 2,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        0 => 'No',
        1 => 'Yes',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_boolean',
  );

  // Exported field_base: 'field_date_of_entry_into_ende'.
  $field_bases['field_date_of_entry_into_ende'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_date_of_entry_into_ende',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'date',
    'settings' => array(
      'cache_count' => 4,
      'cache_enabled' => 0,
      'granularity' => array(
        'day' => 'day',
        'hour' => 0,
        'minute' => 0,
        'month' => 'month',
        'second' => 0,
        'year' => 'year',
      ),
      'timezone_db' => '',
      'todate' => '',
      'tz_handling' => 'none',
    ),
    'translatable' => 0,
    'type' => 'datetime',
  );

  // Exported field_base: 'field_ga_idd_c_cid_number'.
  $field_bases['field_ga_idd_c_cid_number'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_ga_idd_c_cid_number',
    'field_permissions' => array(
      'type' => 2,
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  // Exported field_base: 'field_ind_disability'.
  $field_bases['field_ind_disability'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ind_disability',
    'field_permissions' => array(
      'type' => 2,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'Intellectual disability' => 'Intellectual disability',
        'Autism spectrum disorder' => 'Autism spectrum disorder',
        'Mental illness or psychiatric diagnosis' => 'Mental illness or psychiatric diagnosis',
        'Cerebral palsy' => 'Cerebral palsy',
        'Limited or no vision (legally blind)' => 'Limited or no vision (legally blind)',
        'Hearing loss' => 'Hearing loss',
        'Seizure disorder or neurological problem' => 'Seizure disorder or neurological problem',
        'Other, not listed' => 'Other, not listed',
        'Don\'t know' => 'Don\'t know',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_ind_ethnicity'.
  $field_bases['field_ind_ethnicity'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ind_ethnicity',
    'field_permissions' => array(
      'type' => 2,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'Non-Hispanic' => 'Non-Hispanic',
        'Hispanic' => 'Hispanic',
        'Don\'t know' => 'Don\'t know',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_ind_race'.
  $field_bases['field_ind_race'] = array(
    'active' => 1,
    'cardinality' => -1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_ind_race',
    'field_permissions' => array(
      'type' => 2,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'American Indian or Alaska Native' => 'American Indian or Alaska Native',
        'Asian' => 'Asian',
        'Black or African American' => 'Black or African American',
        'Pacific Islander or Hawaii Native' => 'Pacific Islander or Hawaii Native',
        'White' => 'White',
        'Other race, not listed' => 'Other race, not listed',
        'Don\'t know' => 'Don\'t know',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
