<?php

/**
 * @file
 * minnesota_addition.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function minnesota_addition_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_grp_minn_minimum_wage'.
  $field_bases['field_grp_minn_minimum_wage'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_grp_minn_minimum_wage',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'yes' => 'Earns minimum wage or higher',
        'no' => 'Earns less than minimum wage',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_indv_minn_minimum_wage'.
  $field_bases['field_indv_minn_minimum_wage'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_indv_minn_minimum_wage',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'yes' => 'Earns minimum wage or higher',
        'no' => 'Earns less than minimum wage',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_shl_minn_minimum_wage'.
  $field_bases['field_shl_minn_minimum_wage'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_id_type' => NULL,
    'entity_types' => array(),
    'field_name' => 'field_shl_minn_minimum_wage',
    'field_permissions' => array(
      'type' => 0,
    ),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'yes' => 'Earns minimum wage or higher',
        'no' => 'Earns less than minimum wage',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  return $field_bases;
}
